version: '3.8'
services:
  db:
    container_name: postgres-container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin-container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: secret
      PG_ADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_LISTEN_PORT: 81
    ports:
      - "8081:81"
    networks:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin

networks:
  postgres:
    driver: bridge

volumes:
  db-data:
  pgadmin-data:

