marvelApiPublicKey: 0611500ccb5620d347310076c61af07d
marvelApiPrivateKey: 9bd768bfbbd51ec0adac070ddf5d80b97c5fb89c

server:
  port: 8082
spring:
  application:
    name: superhero-services
  datasource:
    url: jdbc:postgresql://localhost:5432/superhero
    username: postgres
    password: secret
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        order_inserts: true
        jdbc.batch_size: 20
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  zipkin:
    base-url: http://localhost:9411
  rabbitmq:
    addresses: localhost:5672
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: false

